from __future__ import annotations

import json
from pathlib import Path

from vrp_parser import CommandLineParser, ErrorCode, ErrorLine, ParsedCommand

DATA = Path(__file__).parents[1] / "data" / "commands.json"


def test_data_directory_contains_only_runtime_commands() -> None:
    files = sorted(path.name for path in DATA.parent.iterdir() if path.is_file())

    assert files == ["commands.json"]


def test_bundled_commands_are_unique_supported_and_compilable() -> None:
    document = json.loads(DATA.read_text(encoding="utf-8"))
    commands = document["commands"]

    assert commands[:2] == ["#", "TEXT<1-4096>"]
    assert len(commands) == len(set(commands))
    assert all("X.X.X.X" not in item for item in commands)
    assert all("X:X::X:X" not in item for item in commands)
    assert all("}*" not in item and "]*" not in item for item in commands)

    parser = CommandLineParser(document)
    assert parser.command_count == len(commands)


def test_bundled_text_routes_distinguish_comments_commands_and_unknowns() -> None:
    parser = CommandLineParser.from_json_file(DATA)

    comment = parser.parse("! generated by device")
    description = parser.parse("description uplink to core")
    unknown = parser.parse("definitely unknown command")

    assert isinstance(comment, ParsedCommand)
    assert comment.primary_match.original_pattern == "TEXT<1-4096>"
    assert isinstance(description, ParsedCommand)
    assert "description TEXT<1-80>" in {
        match.original_pattern for match in description.matches
    }
    assert description.parameters[0].raw == "uplink to core"
    assert isinstance(unknown, ErrorLine)
    assert unknown.error.code is ErrorCode.UNKNOWN_COMMAND
